### ISSUE TITLE
Would it be possible to merge in the CSS3 transforms patch?

### ISSUE THREAD

**Issue by graingert** [markrcote/flot-axislabels#1]
Would it be possible to merge in the CSS3 transforms patch?

From this commit: https://github.com/dschwen/flot-axislabels/commit/cb1df40758ab3fe27c0177b169abe77e7f39b282

**Comment by markrcote** [comment]
Done.  I extended it to secondary axes as well.  Thanks for pointing it out!  It's a nicer solution than canvas.

**Comment by graingert** [comment]
Thanks for the quick work!
