### ISSUE TITLE
Multiple axes only work when redrawing with $.plot

### ISSUE THREAD

**Issue by magik** [markrcote/flot-axislabels#12]
If you try to use multiple axes with labels, where some axes are not being shown, then using the setData/setupGrid/draw method of redrawing the plot fails.  I believe the problem lies within the "hack" of the secondPass.  When going through the draw method after an axis has gone from not show to show, the first pass section doesn't get re-evaluated and thus it still thinks those axes that are showing now are still not showing.

Not sure if there is going to be an easy fix for this... Seems like it kind of needs the separation between the axes drawing and the plot drawing as your hack comment states...

All in all this is at least somewhat usable if you just redraw by calling the $.plot again.

**Comment by markrcote** [comment]
I think this was fixed in commit 85abc1756d2886fdbc933fb9340d162d5c076f11. Feel free to reopen if not.
