### ISSUE TITLE
Title gets disappeared when the graph is loaded

### ISSUE THREAD

**Issue by krishnaprasad-narayanan** [markrcote/flot-axislabels#15]
Hallo All,

I am using the latest version of flot-axislabels. I have set the xaxes and yaxes title and when I load the graph, the tick labels overrides the axistitle. The title gets disappeared after the graph is loaded. Can somebody guide me to fix this problem?

Thanks
Krishnaprasd

**Comment by markrcote** [comment]
Hm that shouldn't normally happen. You can try setting axisLabelPadding to manually set the distance between the ticks and the label. If that doesn't work, feel free to reopen, but it would be good to have some example code to show the problem.
