### ISSUE TITLE
Internet Explorer 8 throws "Expected identifier" when loading

### ISSUE THREAD

**Issue by gkasparek** [markrcote/flot-axislabels#16]
Have you tested this in IE8 and is it expected to work? I get "Expected identifier" error. I think this is releated to the use of "delete" which maybe is reserved in IE8. I replaced .delete with .dodelete in 3 places and it seems to load fine after that.

**Comment by markrcote** [comment]
I did test this originally in IE 8, though it is possible that something broke in the mean time. I don't have IE 8 handy, though, but I'll try to get a hold of it.

**Comment by markrcote** [comment]
You are very right! I can't find a good explanation for why this happens, but it's fixed now. Sorry for the delay!

**Comment by gkasparek** [comment]
Thanks Mark!

On Sun, Jan 5, 2014 at 5:32 PM, Mark Côté notifications@github.com wrote:

> Closed #16 https://github.com/markrcote/flot-axislabels/issues/16.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/markrcote/flot-axislabels/issues/16
> .

## 

Gil Kasparek
gil@allnight.com
