### ISSUE TITLE
Verify flot-axislabels 2.0 is MIT for all contributors

### ISSUE THREAD

**Issue by mritzman** [markrcote/flot-axislabels#19]
Hi Mark Cote, Xuan Luo, stdexcept, Clemens Stolle and Michael Haddon,

  My name is Matthew Ritzman.  We would like to use your flot-axislabels plugin for a product we are developing.  Due to the fact the original version of flot-axislabels was licensed as GPLv3, our legal team requires us to confirm with you and all the contributors in writing that you are all Ok that the license is MIT for flot-axislabels.  Thank you for your time.

Regards,
Matthew Ritzman

**Comment by markrcote** [comment]
I think that it is unnecessary to contact me, since you can verify that
I added the license in commit 8714ea65312bad8e93ea5d1a7427a63a7951d71e
on 5 April 2012, following the original author's change in commit
a0d11e5ea409a0d9aa625b0ddcbfe05174388d0d to his repo on the same day.

Regardless, yes, I purposefully switched to MIT after getting
confirmation from the original author, Xuan Luo, that he was okay with
it as well. I've pasted that email below for your reference, in case you
are unable to contact him.

Mark

> Sure. I just changed the file.
> 
> On Wed, Apr 4, 2012 at 9:12 PM, Mark Côté mcote@mozilla.com wrote:
> 
> > Hi, I hope I have the right Xuan Luo, the author of the flot-axislabels
> > plug-in (https://github.com/xuanluo/flot-axislabels). If not please
> > disregard this email.
> > 
> > I realize you haven't touched that plug-in in a long time, but I was
> > wondering if you would consider adding another, more permissive license,
> > such as MIT, to your plug-in. I'm the author of a heavily modified fork of
> > flot-axislabels (https://github.com/markrcote/flot-axislabels) which is
> > getting an increasing amount of attention. Given that I was not the primary
> > author, my fork retains the GPLv3 license from yours. However I've realized
> > that, due to the nature of JavaScript plug-ins, I believe that anyone using
> > the flot-axislabels plug-in would have to license their entire application
> > under the GPL or a compatible license. Given that flot itself is under the
> > MIT license, which has (to my knowledge) no such "viral" aspects, I think it
> > would be nice if I could release my plug-in under a similar license.
> > 
> > Thanks very much for making the plug-in in the first place.
> > 
> > Mark Côté
> > Software Developer
> > Mozilla Automation & Tools

**Comment by mritzman** [comment]
Thanks Mark for the response, your response is what our legal team needed even though they could see the commits themselves.
