### ISSUE TITLE
Enhancement: draw label below axis?

### ISSUE THREAD

**Issue by andig** [markrcote/flot-axislabels#21]
I'd like to draw physical units below the actual y-axis so they don't consume any additional vertical space (units don't consume much horizontal space either). This should prevent the axis labels beside the axis from consuming too much screen estate in horizontal direction when using multiple axes. 

Is there an easy way to achieve this?

**Comment by markrcote** [comment]
Not sure I completely understand... could you maybe post a picture?

**Comment by andig** [comment]
I've tried to draw a sample into the volkszaehler.org monitoring app- you can see the desired axis labels (only used for the physical units) in red where they might appear:

![chart](https://cloud.githubusercontent.com/assets/184815/2878156/08a2c96e-d459-11e3-8096-fbcf8db26ac5.png)

I'll think some more about it- maybe sacrificing the last tick label instead is optically more appealing unless axisLabels has a standard feature for this purpose.

**Comment by markrcote** [comment]
Yeah that strikes me as pretty confusing. An alternative might be to put the Y-axis unit into the legend (since the X-axis unit is pretty obvious).

**Comment by andig** [comment]
I've attached it to the 0 value for now as I'll always have one. Alternatively one might try replacing the last (highest) tickMark with the unit. Closing as WFM, thank you!
