### ISSUE TITLE
Does not work with new multiples axis setup

### ISSUE THREAD

**Issue by mivilleb** [markrcote/flot-axislabels#5]
Now that flot accepts multiples axis (not just 2 axes as before but n axes, the plugin only works for the first 2 axes, not the others. 

Any chance that you will publish a revised version?

...
$(function () {
    var data = [
        { data: [[1, 3], [2, 8], [3, 5], [7, 13]], bars: { show: true}, xaxis: 1, yaxis:1},
        { data: [[3, 3], [6, 8], [8, 5], [12, 13]], xaxis: 1, yaxis:2 },
        { data: [[5, 12], [7, 12], null, [7, 2.5], [12, 2.5]], xaxis: 1, yaxis:3 },
        { data: [[2, 3], [7, 8], [9, 5], [10, 13], [11,12]], xaxis: 1, yaxis: 4 }
    ];

```
$.plot($("#placeholder"),
                  data,
                  {
                      xaxes: [
                          { position: 'bottom' }
                      ],
                      yaxes: [
                          { position: 'left', axisLabel: 'Hourly Rain (mm)', axisLabelPadding: 10, axisLabelUseCanvas: true, axisLabelFontSizePixels: 12, axisLabelFontFamily: 'Arial' },
                          { position: 'right', axisLabel: 'Temperature (C)', axisLabelPadding: 20, axisLabelUseCanvas: true, axisLabelFontSizePixels: 12, axisLabelFontFamily: 'Arial' },
                          { position: 'right', axisLabel: 'Relative Humidity (%)', axisLabelPadding: 20, axisLabelUseCanvas: true, axisLabelFontSizePixels: 12, axisLabelFontFamily: 'Arial' },
                          { position: 'right',axisLabel: 'Pressure (hPa)', axisLabelPadding: 20, axisLabelUseCanvas: true, axisLabelFontSizePixels: 12, axisLabelFontFamily: 'Arial' }
                      ],
                      grid: { hoverable: true, show: true }
                  });
```

});
...

**Comment by markrcote** [comment]
I'll look into it if I find some time.  Thanks for mentioning it.

**Comment by mivilleb** [comment]
Thanks, I am using this to provide meteogram to humanitarian agencies working in remote areas as part of the Vetero project.

Example done with Highcharts:

[Meteogram](http://ops.vetero.info/meteogram_xml_table_ops.php?ops=4&code=MTPP)

I would like to use flot instead of Highcharts mainly because Highcharts outputs is now in SVG and it currently does not work with the default Android browser. While flot and jqPlot work fine. I could use jqPlot instead which already handles multiple axes title, but it does not have a plugin for plotting directional field like wind speed and direction (x,y,angle), mainly an arrow.

**Comment by markrcote** [comment]
I made some good progress on this today and appear to have canvas labels working properly with n axes. I want to get the other renderers working, then I'll commit my changes. Should be this week sometime.

**Comment by markrcote** [comment]
This should be working for canvas, CSS, and HTML modes. I'll get to IE transforms when I have time (if they're even still needed... I never use IE). I even managed to simplify the code in a few places. Let me know if this works for you!

**Comment by mivilleb** [comment]
Just tried it and it works perfectly in Chrome and Firefox on Lubuntu 11.10. Will try later on IE. Thank you so much for all your hard work. This brings flot to another level and more people will now use flot because of your plugin. When you are ready you should announce it in this issue:
http://code.google.com/p/flot/issues/detail?id=42

Do you know if your plugin will be compatible with flotr2:

http://www.humblesoftware.com/flotr2/

BTW, I am also from Montreal, but now live in New Zealand.

Merci,

Bernard

**Comment by mivilleb** [comment]
Sorry, the flotr2 fork does not do multiple axes, so never mind.

**Comment by markrcote** [comment]
It probably won't work quite properly in IE at the moment. I played with it a bit, but I'm having a hard time even getting flot itself to work in IE 9. Not sure what's going on there. Shouldn't require more than a couple tweaks anyway.

**Comment by markrcote** [comment]
Okay got it working; I forgot to use excanvas while testing.  Seems that axis labels rendered in canvas don't work with IE 8, but the default mode (IE transforms + CSS positioning) seems to work perfectly.  I wouldn't force canvas (via axisLabelUseCanvas) unless you really need to, for some reason.  flot-axislabels defaults to CSS transforms and will gracefully fall back to canvas and then plain HTML/CSS positioning, depending on the browser.  I don't think it's worth trying to get canvas labels working in IE 8 unless there's a really good reason.

**Comment by markrcote** [comment]
Also, if it's all right with you, I'd like to use (a slightly modified version of) your example data above to construct a public example of flot-axislabels usage.  It looks better than contrived graphs with labels like "foo" and "bar". :)

**Comment by mivilleb** [comment]
Of course, it's your code, please go ahead. Once I have real data, I will give you a link to how I am using it.

Cheers,

Bernard Miville

**Comment by mivilleb** [comment]
In your readme file you mention that the appearance of the label can be changed using the id of the div (e.g. #y2axisLabel), actually it seems that there is only a class instead called #xaxisLabel or #y2axisLabel etc. So in the css stylesheet you need to use .y2axisLabel  etc. to change the appearance and not #y2axisLabel.

**Comment by mivilleb** [comment]
Actually using .axisLabels does a better job of changing the font size as it preserves the padding and changes all the labels for all the axes. 

...css
.axisLabels {
    font-size: 12px;
}
...

**Comment by markrcote** [comment]
Thanks, I was going to update the README about the axisLabels class, but I'm glad you caught the id vs class mistake.  I went with classes in both cases because there might be more than one graph on a page.

If you're satisfied with these changes, feel free to close this issue.  I'll probably do a blog post about it at http://cloquewerk.livejournal.com/ at some point to broadcast the improvements.

**Comment by mivilleb** [comment]
Hi tried it with Intenet Explorer 8 and it worked perfectly. Thanks for the plugin upgrade.

Cheers,

Bernard Miville
